bootstrap: try to not overwrite existing files

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -27,7 +27,18 @@ else
 fi
 
 if existence libtool || existence libtoolize || existence glibtoolize || existence slibtool; then
-    autoreconf -I m4 -i ${1+"$@"}
+    echo "Running autoreconf..."
+    if ! autoreconf ${1+"$@"} -Werror ; then
+        echo "Failed to autoreconf without installing new files, retrying with installing missing files..."
+        if ! autoreconf -i ${1+"$@"} ; then
+            echo "Failed to autoreconf, retrying with force install..."
+            if ! autoreconf -i -f ${1+"$@"} ; then
+                echo "*** Failed to create 'configure' and other autotools generated files. ***" >&2
+                exit 1
+            fi
+        fi
+    fi
+    echo "The ${bs_scrdir-.}/configure is ready to run."
 else
     echo "*** No libtoolize (libtool) or libtool found, please install it ***" >&2;
     exit 1
